In [14]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

DATA_DIR = '/content/drive/MyDrive/TimeSeriesDeepLearning_FIM601/kaggle_data/optiver-realized-volatility-prediction'

Mounted at /content/drive

In [15]:
trade_train = pd.read_parquet(f"{DATA_DIR}/trade_train.parquet")
book_train = pd.read_parquet(f"{DATA_DIR}/book_train.parquet")
trade_test = pd.read_parquet(f"{DATA_DIR}/trade_test.parquet")
book_test = pd.read_parquet(f"{DATA_DIR}/book_test.parquet")

## Data Breakdown

### Book Data
* `time_id`: The dataset is composed of 10 minute blocks. Each 10 minute block is uniquely identified by its `time_id`. 
* `seconds_in_bucket`: The amount of seconds that has elapsed since the beginning of the bucket identified by `time_id`. This is a snapshot of the market at this particular time. If a particular second is missing, it is assumed that the market is unchanged from the last entry. 
* `[bid/ask]_price[1/2]`: Exactly what it sounds like. `bid_price2` < `bid_price1` < `ask_price1` < `ask_price2`. 
* `stock_id`: Unique stock identifier. 

### Trade Data

In [29]:
trade_train[(trade_train['stock_id'] == 0) & (trade_train['time_id'] == 5)]

    time_id  seconds_in_bucket     price  size  order_count stock_id
0         5                 21  1.002301   326           12        0
1         5                 46  1.002778   128            4        0
2         5                 50  1.002818    55            1        0
3         5                 57  1.003155   121            5        0
4         5                 68  1.003646     4            1        0
5         5                 78  1.003762   134            5        0
6         5                122  1.004207   102            3        0
7         5                127  1.004577     1            1        0
8         5                144  1.004370     6            1        0
9         5                147  1.003964   233            4        0
10        5                177  1.003853     1            1        0
11        5                183  1.003956     2            1        0
12        5                187  1.004267   165            2        0
13        5                207  1.003543    72            4        0
14        5                218  1.004155    33            5        0
15        5                254  1.003905   100            1        0
16        5                263  1.003905     1            1        0
17        5                265  1.004111     2            2        0
18        5                278  1.004370   106            2        0
19        5                331  1.004680     3            2        0
20        5                366  1.004215     6            2        0
21        5                380  1.004116   432            9        0
22        5                389  1.004422     1            1        0
23        5                398  1.004215   100            1        0
24        5                430  1.003853     2            1        0
25        5                435  1.003905     1            1        0
26        5                464  1.003749     2            1        0
27        5                470  1.003465   200            7        0
28        5                471  1.003646   101            2        0
29        5                488  1.003905     2            1        0
30        5                514  1.004012    29            3        0
31        5                523  1.004008     1            1        0
32        5                540  1.003543     4            1        0
33        5                549  1.003129     2            1        0
34        5                550  1.002799    13            3        0
35        5                551  1.002561   154            5        0
36        5                562  1.002715     1            1        0
37        5                572  1.003191   499            6        0
38        5                581  1.003478     8            3        0
39        5                585  1.003646    26            2        0

In [28]:
book_train[(book_train['stock_id'] == 0) & (book_train['time_id'] == 5)]

,time_id,seconds_in_bucket,bid_price1,ask_price1,bid_price2,ask_price2,bid_size1,ask_size1,bid_size2,ask_size2,stock_id
0,5,0,1.001422,1.002301,1.001370,1.002353,3,226,2,100,0
1,5,1,1.001422,1.002301,1.001370,1.002353,3,100,2,100,0
2,5,5,1.001422,1.002301,1.001370,1.002405,3,100,2,100,0
3,5,6,1.001422,1.002301,1.001370,1.002405,3,126,2,100,0
4,5,7,1.001422,1.002301,1.001370,1.002405,3,126,2,100,0
...,...,...,...,...,...,...,...,...,...,...,...
297,5,585,1.003129,1.003749,1.003025,1.003801,100,3,26,3,0
298,5,586,1.003129,1.003749,1.002612,1.003801,100,3,2,3,0
299,5,587,1.003129,1.003749,1.003025,1.003801,100,3,26,3,0
300,5,588,1.003129,1.003749,1.002612,1.003801,100,3,2,3,0
301,5,593,1.003129,1.003749,1.003025,1.003801,100,3,26,3,0